import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// ============================================
// TOOL DATA - Initial 50 Tools
// ============================================

const tools = [
  // PROJECT MANAGEMENT (8)
  {
    name: 'jira',
    displayName: 'Jira',
    category: 'PROJECT_MANAGEMENT',
    aliases: ['atlassian jira', 'jira software'],
    primaryUseCases: ['issue tracking', 'sprint planning', 'agile project management', 'bug tracking'],
    keyFeatures: ['kanban boards', 'scrum boards', 'roadmaps', 'reporting', 'automation'],
    complexity: 'ADVANCED',
    typicalPricingTier: 'PROFESSIONAL',
    estimatedCostPerUser: 8.15,
    hasFreeForever: true,
    bestForTeamSize: ['MEDIUM', 'LARGE', 'ENTERPRISE'],
    bestForStage: ['GROWTH', 'ESTABLISHED'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: true,
    selfHosted: true,
    airGapped: true,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI-powered issue suggestions and automation',
    websiteUrl: 'https://www.atlassian.com/software/jira',
  },
  {
    name: 'linear',
    displayName: 'Linear',
    category: 'PROJECT_MANAGEMENT',
    aliases: ['linear app', 'linear.app'],
    primaryUseCases: ['issue tracking', 'sprint planning', 'product roadmaps'],
    keyFeatures: ['keyboard shortcuts', 'cycles', 'roadmaps', 'github sync', 'fast UI'],
    complexity: 'MODERATE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 8.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: false,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI-powered triage, writing assistance',
    websiteUrl: 'https://linear.app',
  },
  {
    name: 'asana',
    displayName: 'Asana',
    category: 'PROJECT_MANAGEMENT',
    aliases: ['asana work management'],
    primaryUseCases: ['project management', 'task tracking', 'workflow automation', 'team coordination'],
    keyFeatures: ['timeline', 'portfolios', 'workload', 'forms', 'rules automation'],
    complexity: 'MODERATE',
    typicalPricingTier: 'PROFESSIONAL',
    estimatedCostPerUser: 10.99,
    hasFreeForever: true,
    bestForTeamSize: ['SMALL', 'MEDIUM', 'LARGE'],
    bestForStage: ['PRE_SEED', 'EARLY_SEED', 'GROWTH', 'ESTABLISHED'],
    bestForTechSavviness: ['NEWBIE', 'DECENT', 'NINJA'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: true,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'Smart status updates, AI goal recommendations',
    websiteUrl: 'https://asana.com',
  },
  {
    name: 'trello',
    displayName: 'Trello',
    category: 'PROJECT_MANAGEMENT',
    aliases: ['atlassian trello'],
    primaryUseCases: ['kanban boards', 'simple task management', 'visual project tracking'],
    keyFeatures: ['boards', 'lists', 'cards', 'power-ups', 'butler automation'],
    complexity: 'SIMPLE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 5.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED'],
    bestForTechSavviness: ['NEWBIE', 'DECENT'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: true,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI-powered card suggestions',
    websiteUrl: 'https://trello.com',
  },
  {
    name: 'monday',
    displayName: 'Monday.com',
    category: 'PROJECT_MANAGEMENT',
    aliases: ['monday work os', 'monday.com'],
    primaryUseCases: ['work management', 'project tracking', 'CRM', 'workflow automation'],
    keyFeatures: ['customizable boards', 'automations', 'integrations', 'dashboards', 'forms'],
    complexity: 'MODERATE',
    typicalPricingTier: 'PROFESSIONAL',
    estimatedCostPerUser: 9.00,
    hasFreeForever: true,
    bestForTeamSize: ['SMALL', 'MEDIUM', 'LARGE'],
    bestForStage: ['PRE_SEED', 'EARLY_SEED', 'GROWTH', 'ESTABLISHED'],
    bestForTechSavviness: ['NEWBIE', 'DECENT', 'NINJA'],
    soc2: true,
    hipaa: true,
    gdpr: true,
    euDataResidency: true,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI assistant for task creation and automation',
    websiteUrl: 'https://monday.com',
  },
  {
    name: 'clickup',
    displayName: 'ClickUp',
    category: 'PROJECT_MANAGEMENT',
    aliases: ['click up'],
    primaryUseCases: ['project management', 'docs', 'goals', 'time tracking'],
    keyFeatures: ['everything app', 'docs', 'whiteboards', 'goals', 'time tracking'],
    complexity: 'ADVANCED',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 7.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM', 'LARGE'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    soc2: true,
    hipaa: true,
    gdpr: true,
    euDataResidency: true,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'ClickUp AI for writing, summarizing, and task management',
    websiteUrl: 'https://clickup.com',
  },
  {
    name: 'basecamp',
    displayName: 'Basecamp',
    category: 'PROJECT_MANAGEMENT',
    aliases: ['basecamp 4', '37signals basecamp'],
    primaryUseCases: ['project management', 'team communication', 'client collaboration'],
    keyFeatures: ['message boards', 'to-dos', 'schedules', 'docs', 'check-ins'],
    complexity: 'SIMPLE',
    typicalPricingTier: 'PROFESSIONAL',
    estimatedCostPerUser: 15.00,
    hasFreeForever: false,
    bestForTeamSize: ['SMALL', 'MEDIUM'],
    bestForStage: ['PRE_SEED', 'EARLY_SEED', 'GROWTH'],
    bestForTechSavviness: ['NEWBIE', 'DECENT'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: false,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: false,
    websiteUrl: 'https://basecamp.com',
  },
  {
    name: 'shortcut',
    displayName: 'Shortcut',
    category: 'PROJECT_MANAGEMENT',
    aliases: ['shortcut app', 'clubhouse'],
    primaryUseCases: ['issue tracking', 'project planning', 'roadmaps', 'agile workflows'],
    keyFeatures: ['stories', 'epics', 'iterations', 'roadmaps', 'GitHub integration'],
    complexity: 'MODERATE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 8.50,
    hasFreeForever: true,
    bestForTeamSize: ['SMALL', 'MEDIUM', 'LARGE'],
    bestForStage: ['PRE_SEED', 'EARLY_SEED', 'GROWTH', 'ESTABLISHED'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: false,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI-powered story suggestions and automation',
    websiteUrl: 'https://shortcut.com',
  },

  // DOCUMENTATION (6)
  {
    name: 'notion',
    displayName: 'Notion',
    category: 'DOCUMENTATION',
    aliases: ['notion app', 'notion.so'],
    primaryUseCases: ['documentation', 'wikis', 'project management', 'notes'],
    keyFeatures: ['blocks', 'databases', 'templates', 'collaboration', 'API'],
    complexity: 'MODERATE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 8.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM', 'LARGE'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH', 'ESTABLISHED'],
    bestForTechSavviness: ['NEWBIE', 'DECENT', 'NINJA'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: true,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'Notion AI for writing, summarizing, Q&A',
    websiteUrl: 'https://notion.so',
  },
  {
    name: 'confluence',
    displayName: 'Confluence',
    category: 'DOCUMENTATION',
    aliases: ['atlassian confluence'],
    primaryUseCases: ['team wiki', 'documentation', 'knowledge management'],
    keyFeatures: ['spaces', 'pages', 'templates', 'macros', 'Jira integration'],
    complexity: 'ADVANCED',
    typicalPricingTier: 'PROFESSIONAL',
    estimatedCostPerUser: 6.05,
    hasFreeForever: true,
    bestForTeamSize: ['MEDIUM', 'LARGE', 'ENTERPRISE'],
    bestForStage: ['GROWTH', 'ESTABLISHED'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: true,
    selfHosted: true,
    airGapped: true,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI-powered search and content suggestions',
    websiteUrl: 'https://www.atlassian.com/software/confluence',
  },
  {
    name: 'coda',
    displayName: 'Coda',
    category: 'DOCUMENTATION',
    aliases: ['coda doc', 'coda.io'],
    primaryUseCases: ['docs', 'spreadsheets', 'apps', 'automation'],
    keyFeatures: ['packs', 'formulas', 'automation', 'cross-doc', 'templates'],
    complexity: 'ADVANCED',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 10.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM'],
    bestForStage: ['PRE_SEED', 'EARLY_SEED', 'GROWTH'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: false,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'Coda AI for writing and data analysis',
    websiteUrl: 'https://coda.io',
  },
  {
    name: 'slite',
    displayName: 'Slite',
    category: 'DOCUMENTATION',
    aliases: ['slite.com'],
    primaryUseCases: ['team wiki', 'documentation', 'knowledge base'],
    keyFeatures: ['channels', 'templates', 'search', 'integrations'],
    complexity: 'SIMPLE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 8.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED'],
    bestForTechSavviness: ['NEWBIE', 'DECENT'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: true,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI-powered Q&A and content suggestions',
    websiteUrl: 'https://slite.com',
  },
  {
    name: 'gitbook',
    displayName: 'GitBook',
    category: 'DOCUMENTATION',
    aliases: ['git book'],
    primaryUseCases: ['technical documentation', 'API docs', 'public docs'],
    keyFeatures: ['git sync', 'versioning', 'customization', 'analytics'],
    complexity: 'MODERATE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 6.70,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM'],
    bestForStage: ['PRE_SEED', 'EARLY_SEED', 'GROWTH'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: false,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI-powered search and documentation assistance',
    websiteUrl: 'https://gitbook.com',
  },
  {
    name: 'almanac',
    displayName: 'Almanac',
    category: 'DOCUMENTATION',
    aliases: ['almanac.io'],
    primaryUseCases: ['documentation', 'handbooks', 'async collaboration'],
    keyFeatures: ['smart docs', 'templates', 'approvals', 'version control'],
    complexity: 'MODERATE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 9.00,
    hasFreeForever: true,
    bestForTeamSize: ['SMALL', 'MEDIUM'],
    bestForStage: ['PRE_SEED', 'EARLY_SEED', 'GROWTH'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: false,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI writing assistant',
    websiteUrl: 'https://almanac.io',
  },

  // COMMUNICATION (5)
  {
    name: 'slack',
    displayName: 'Slack',
    category: 'COMMUNICATION',
    aliases: ['slack app', 'salesforce slack'],
    primaryUseCases: ['team messaging', 'channels', 'integrations', 'huddles'],
    keyFeatures: ['channels', 'threads', 'apps', 'workflows', 'huddles'],
    complexity: 'MODERATE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 8.75,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH', 'ESTABLISHED'],
    bestForTechSavviness: ['NEWBIE', 'DECENT', 'NINJA'],
    soc2: true,
    hipaa: true,
    gdpr: true,
    euDataResidency: true,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'Slack AI for search, summaries, and recaps',
    websiteUrl: 'https://slack.com',
  },
  {
    name: 'discord',
    displayName: 'Discord',
    category: 'COMMUNICATION',
    aliases: ['discord app'],
    primaryUseCases: ['community', 'voice chat', 'messaging', 'gaming'],
    keyFeatures: ['servers', 'voice channels', 'bots', 'threads', 'stages'],
    complexity: 'MODERATE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 0,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    soc2: false,
    hipaa: false,
    gdpr: true,
    euDataResidency: false,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: false,
    websiteUrl: 'https://discord.com',
  },
  {
    name: 'teams',
    displayName: 'Microsoft Teams',
    category: 'COMMUNICATION',
    aliases: ['microsoft teams', 'ms teams'],
    primaryUseCases: ['team messaging', 'video calls', 'file sharing', 'collaboration'],
    keyFeatures: ['channels', 'meetings', 'Office integration', 'apps', 'tabs'],
    complexity: 'MODERATE',
    typicalPricingTier: 'PROFESSIONAL',
    estimatedCostPerUser: 4.00,
    hasFreeForever: true,
    bestForTeamSize: ['MEDIUM', 'LARGE', 'ENTERPRISE'],
    bestForStage: ['GROWTH', 'ESTABLISHED'],
    bestForTechSavviness: ['NEWBIE', 'DECENT', 'NINJA'],
    soc2: true,
    hipaa: true,
    gdpr: true,
    euDataResidency: true,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'Copilot AI for meetings and chat',
    websiteUrl: 'https://teams.microsoft.com',
  },
  {
    name: 'loom',
    displayName: 'Loom',
    category: 'COMMUNICATION',
    aliases: ['loom video', 'loom.com'],
    primaryUseCases: ['async video', 'screen recording', 'video messaging'],
    keyFeatures: ['screen recording', 'transcripts', 'comments', 'analytics'],
    complexity: 'SIMPLE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 12.50,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM', 'LARGE'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH', 'ESTABLISHED'],
    bestForTechSavviness: ['NEWBIE', 'DECENT', 'NINJA'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: false,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI-generated titles, summaries, and chapters',
    websiteUrl: 'https://loom.com',
  },
  {
    name: 'zoom',
    displayName: 'Zoom',
    category: 'COMMUNICATION',
    aliases: ['zoom meetings', 'zoom video'],
    primaryUseCases: ['video conferencing', 'webinars', 'screen sharing'],
    keyFeatures: ['meetings', 'webinars', 'breakout rooms', 'recording', 'whiteboard'],
    complexity: 'SIMPLE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 13.33,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH', 'ESTABLISHED'],
    bestForTechSavviness: ['NEWBIE', 'DECENT', 'NINJA'],
    soc2: true,
    hipaa: true,
    gdpr: true,
    euDataResidency: true,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI Companion for summaries and smart recording',
    websiteUrl: 'https://zoom.us',
  },

  // DEVELOPMENT (6)
  {
    name: 'github',
    displayName: 'GitHub',
    category: 'DEVELOPMENT',
    aliases: ['github.com', 'gh'],
    primaryUseCases: ['version control', 'code hosting', 'CI/CD', 'collaboration'],
    keyFeatures: ['repos', 'pull requests', 'actions', 'issues', 'copilot'],
    complexity: 'MODERATE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 4.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH', 'ESTABLISHED'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: true,
    selfHosted: true,
    airGapped: true,
    hasAiFeatures: true,
    aiFeatureDescription: 'Copilot AI for code completion and chat',
    websiteUrl: 'https://github.com',
  },
  {
    name: 'gitlab',
    displayName: 'GitLab',
    category: 'DEVELOPMENT',
    aliases: ['gitlab.com'],
    primaryUseCases: ['version control', 'CI/CD', 'DevSecOps', 'code review'],
    keyFeatures: ['repos', 'merge requests', 'CI/CD', 'security', 'packages'],
    complexity: 'ADVANCED',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 19.00,
    hasFreeForever: true,
    bestForTeamSize: ['SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE'],
    bestForStage: ['PRE_SEED', 'EARLY_SEED', 'GROWTH', 'ESTABLISHED'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: true,
    selfHosted: true,
    airGapped: true,
    hasAiFeatures: true,
    aiFeatureDescription: 'GitLab Duo AI for code suggestions and chat',
    websiteUrl: 'https://gitlab.com',
  },
  {
    name: 'cursor',
    displayName: 'Cursor',
    category: 'DEVELOPMENT',
    aliases: ['cursor ai', 'cursor.sh', 'cursor editor'],
    primaryUseCases: ['AI coding', 'code editing', 'pair programming'],
    keyFeatures: ['AI chat', 'code generation', 'codebase understanding', 'VS Code fork'],
    complexity: 'MODERATE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 20.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    soc2: false,
    hipaa: false,
    gdpr: true,
    euDataResidency: false,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI-first code editor with Claude/GPT integration',
    websiteUrl: 'https://cursor.sh',
  },
  {
    name: 'vscode',
    displayName: 'VS Code',
    category: 'DEVELOPMENT',
    aliases: ['visual studio code', 'vsc'],
    primaryUseCases: ['code editing', 'debugging', 'extensions'],
    keyFeatures: ['extensions', 'debugging', 'git integration', 'terminal'],
    complexity: 'MODERATE',
    typicalPricingTier: 'FREE',
    estimatedCostPerUser: 0,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH', 'ESTABLISHED'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    soc2: false,
    hipaa: false,
    gdpr: true,
    euDataResidency: false,
    selfHosted: false,
    airGapped: true,
    hasAiFeatures: false,
    websiteUrl: 'https://code.visualstudio.com',
  },
  {
    name: 'vercel',
    displayName: 'Vercel',
    category: 'DEVELOPMENT',
    aliases: ['vercel.com', 'zeit'],
    primaryUseCases: ['frontend hosting', 'serverless', 'edge functions', 'deployment'],
    keyFeatures: ['preview deployments', 'edge network', 'analytics', 'CI/CD'],
    complexity: 'MODERATE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 20.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM', 'LARGE'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH', 'ESTABLISHED'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    soc2: true,
    hipaa: true,
    gdpr: true,
    euDataResidency: true,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'v0 AI for UI generation',
    websiteUrl: 'https://vercel.com',
  },
  {
    name: 'railway',
    displayName: 'Railway',
    category: 'DEVELOPMENT',
    aliases: ['railway.app'],
    primaryUseCases: ['app hosting', 'databases', 'deployment', 'infrastructure'],
    keyFeatures: ['instant deployments', 'databases', 'cron jobs', 'private networking'],
    complexity: 'SIMPLE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 5.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: false,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: false,
    websiteUrl: 'https://railway.app',
  },

  // DESIGN (5)
  {
    name: 'figma',
    displayName: 'Figma',
    category: 'DESIGN',
    aliases: ['figma.com'],
    primaryUseCases: ['UI design', 'prototyping', 'collaboration', 'design systems'],
    keyFeatures: ['components', 'auto-layout', 'prototyping', 'dev mode', 'plugins'],
    complexity: 'MODERATE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 15.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH', 'ESTABLISHED'],
    bestForTechSavviness: ['NEWBIE', 'DECENT', 'NINJA'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: true,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI features for design generation and editing',
    websiteUrl: 'https://figma.com',
  },
  {
    name: 'framer',
    displayName: 'Framer',
    category: 'DESIGN',
    aliases: ['framer.com'],
    primaryUseCases: ['website building', 'prototyping', 'no-code sites'],
    keyFeatures: ['visual editor', 'components', 'CMS', 'animations', 'AI site builder'],
    complexity: 'MODERATE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 15.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    soc2: false,
    hipaa: false,
    gdpr: true,
    euDataResidency: false,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI site generation and content writing',
    websiteUrl: 'https://framer.com',
  },
  {
    name: 'canva',
    displayName: 'Canva',
    category: 'DESIGN',
    aliases: ['canva.com'],
    primaryUseCases: ['graphic design', 'presentations', 'social media', 'video'],
    keyFeatures: ['templates', 'brand kit', 'magic resize', 'collaboration', 'video'],
    complexity: 'SIMPLE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 13.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM', 'LARGE'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH', 'ESTABLISHED'],
    bestForTechSavviness: ['NEWBIE', 'DECENT'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: false,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'Magic Studio AI for design generation and editing',
    websiteUrl: 'https://canva.com',
  },
  {
    name: 'miro',
    displayName: 'Miro',
    category: 'DESIGN',
    aliases: ['miro.com', 'realtimeboard'],
    primaryUseCases: ['whiteboarding', 'diagramming', 'brainstorming', 'workshops'],
    keyFeatures: ['infinite canvas', 'templates', 'voting', 'timer', 'integrations'],
    complexity: 'SIMPLE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 8.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM', 'LARGE'],
    bestForStage: ['PRE_SEED', 'EARLY_SEED', 'GROWTH', 'ESTABLISHED'],
    bestForTechSavviness: ['NEWBIE', 'DECENT', 'NINJA'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: true,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'Miro AI for ideation and clustering',
    websiteUrl: 'https://miro.com',
  },
  {
    name: 'figjam',
    displayName: 'FigJam',
    category: 'DESIGN',
    aliases: ['fig jam'],
    primaryUseCases: ['whiteboarding', 'brainstorming', 'diagramming'],
    keyFeatures: ['sticky notes', 'shapes', 'stamps', 'widgets', 'voting'],
    complexity: 'SIMPLE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 5.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM', 'LARGE'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH', 'ESTABLISHED'],
    bestForTechSavviness: ['NEWBIE', 'DECENT', 'NINJA'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: true,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI features for brainstorming and sorting',
    websiteUrl: 'https://figma.com/figjam',
  },

  // MEETINGS (5)
  {
    name: 'fireflies',
    displayName: 'Fireflies.ai',
    category: 'MEETINGS',
    aliases: ['fireflies', 'fireflies ai'],
    primaryUseCases: ['meeting transcription', 'note-taking', 'call recording'],
    keyFeatures: ['transcription', 'search', 'action items', 'integrations', 'AI summary'],
    complexity: 'SIMPLE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 10.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM', 'LARGE'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH', 'ESTABLISHED'],
    bestForTechSavviness: ['NEWBIE', 'DECENT', 'NINJA'],
    soc2: true,
    hipaa: true,
    gdpr: true,
    euDataResidency: false,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI transcription, summaries, and action items',
    websiteUrl: 'https://fireflies.ai',
  },
  {
    name: 'otter',
    displayName: 'Otter.ai',
    category: 'MEETINGS',
    aliases: ['otter', 'otter ai'],
    primaryUseCases: ['meeting transcription', 'note-taking', 'live captions'],
    keyFeatures: ['live transcription', 'summaries', 'action items', 'speaker ID'],
    complexity: 'SIMPLE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 16.99,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH'],
    bestForTechSavviness: ['NEWBIE', 'DECENT', 'NINJA'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: false,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI transcription and meeting intelligence',
    websiteUrl: 'https://otter.ai',
  },
  {
    name: 'grain',
    displayName: 'Grain',
    category: 'MEETINGS',
    aliases: ['grain.com', 'grain video'],
    primaryUseCases: ['meeting recording', 'highlights', 'sharing', 'coaching'],
    keyFeatures: ['auto-highlights', 'clips', 'transcription', 'integrations'],
    complexity: 'SIMPLE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 15.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM'],
    bestForStage: ['PRE_SEED', 'EARLY_SEED', 'GROWTH'],
    bestForTechSavviness: ['NEWBIE', 'DECENT', 'NINJA'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: false,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI-powered highlights and summaries',
    websiteUrl: 'https://grain.com',
  },
  {
    name: 'fathom',
    displayName: 'Fathom',
    category: 'MEETINGS',
    aliases: ['fathom video', 'fathom.video'],
    primaryUseCases: ['meeting recording', 'transcription', 'summaries'],
    keyFeatures: ['auto-recording', 'summaries', 'highlights', 'CRM sync'],
    complexity: 'SIMPLE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 19.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM'],
    bestForStage: ['PRE_SEED', 'EARLY_SEED', 'GROWTH'],
    bestForTechSavviness: ['NEWBIE', 'DECENT'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: false,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI meeting summaries and action items',
    websiteUrl: 'https://fathom.video',
  },
  {
    name: 'tldv',
    displayName: 'tl;dv',
    category: 'MEETINGS',
    aliases: ['tldv', 'tl dv', 'too long didnt view'],
    primaryUseCases: ['meeting recording', 'transcription', 'clips'],
    keyFeatures: ['recording', 'transcription', 'timestamps', 'clips', 'sharing'],
    complexity: 'SIMPLE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 20.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH'],
    bestForTechSavviness: ['NEWBIE', 'DECENT', 'NINJA'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: true,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI meeting notes and summaries',
    websiteUrl: 'https://tldv.io',
  },

  // AUTOMATION (4)
  {
    name: 'zapier',
    displayName: 'Zapier',
    category: 'AUTOMATION',
    aliases: ['zapier.com'],
    primaryUseCases: ['workflow automation', 'app integration', 'no-code automation'],
    keyFeatures: ['zaps', 'multi-step', 'filters', 'paths', 'tables'],
    complexity: 'MODERATE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 19.99,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM', 'LARGE'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH', 'ESTABLISHED'],
    bestForTechSavviness: ['NEWBIE', 'DECENT', 'NINJA'],
    soc2: true,
    hipaa: true,
    gdpr: true,
    euDataResidency: true,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI actions for data processing and generation',
    websiteUrl: 'https://zapier.com',
  },
  {
    name: 'make',
    displayName: 'Make',
    category: 'AUTOMATION',
    aliases: ['make.com', 'integromat'],
    primaryUseCases: ['workflow automation', 'visual automation', 'integration'],
    keyFeatures: ['visual builder', 'scenarios', 'modules', 'data transformation'],
    complexity: 'ADVANCED',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 9.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM'],
    bestForStage: ['PRE_SEED', 'EARLY_SEED', 'GROWTH'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: true,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI modules for content generation',
    websiteUrl: 'https://make.com',
  },
  {
    name: 'n8n',
    displayName: 'n8n',
    category: 'AUTOMATION',
    aliases: ['n8n.io'],
    primaryUseCases: ['workflow automation', 'self-hosted automation', 'integration'],
    keyFeatures: ['visual builder', 'self-hosted', 'code nodes', 'fair-code'],
    complexity: 'ADVANCED',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 20.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM'],
    bestForStage: ['PRE_SEED', 'EARLY_SEED', 'GROWTH'],
    bestForTechSavviness: ['NINJA'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: true,
    selfHosted: true,
    airGapped: true,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI agent nodes for autonomous workflows',
    websiteUrl: 'https://n8n.io',
  },
  {
    name: 'pipedream',
    displayName: 'Pipedream',
    category: 'AUTOMATION',
    aliases: ['pipedream.com'],
    primaryUseCases: ['API integration', 'workflow automation', 'developer automation'],
    keyFeatures: ['code-first', 'pre-built triggers', 'HTTP endpoints', 'databases'],
    complexity: 'ADVANCED',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 19.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM'],
    bestForStage: ['PRE_SEED', 'EARLY_SEED', 'GROWTH'],
    bestForTechSavviness: ['NINJA'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: false,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI code generation for workflows',
    websiteUrl: 'https://pipedream.com',
  },

  // AI ASSISTANTS (12)
  {
    name: 'chatgpt',
    displayName: 'ChatGPT',
    category: 'AI_ASSISTANTS',
    aliases: ['openai chatgpt', 'chat gpt', 'gpt-4', 'gpt4', 'chatgpt plus', 'chatgpt team'],
    primaryUseCases: ['AI chat', 'writing assistance', 'coding help', 'analysis', 'research'],
    keyFeatures: ['conversation', 'GPTs', 'code interpreter', 'canvas', 'vision', 'voice', 'memory'],
    complexity: 'SIMPLE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 20.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH', 'ESTABLISHED'],
    bestForTechSavviness: ['NEWBIE', 'DECENT', 'NINJA'],
    soc2: true,
    hipaa: true,
    gdpr: true,
    euDataResidency: true,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'GPT-4o and o1 for general AI assistance with vision and voice',
    websiteUrl: 'https://chat.openai.com',
  },
  {
    name: 'claude',
    displayName: 'Claude',
    category: 'AI_ASSISTANTS',
    aliases: ['anthropic claude', 'claude ai', 'claude.ai', 'claude pro', 'claude teams'],
    primaryUseCases: ['AI chat', 'writing', 'analysis', 'coding', 'research', 'document analysis'],
    keyFeatures: ['long context', 'artifacts', 'projects', 'analysis', 'vision', 'computer use', 'MCP'],
    complexity: 'SIMPLE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 20.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH', 'ESTABLISHED'],
    bestForTechSavviness: ['NEWBIE', 'DECENT', 'NINJA'],
    soc2: true,
    hipaa: true,
    gdpr: true,
    euDataResidency: true,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'Claude Opus 4.5 and Sonnet 4 for AI assistance with artifacts and computer use',
    websiteUrl: 'https://claude.ai',
  },
  {
    name: 'claude-code',
    displayName: 'Claude Code',
    category: 'AI_ASSISTANTS',
    aliases: ['claude code', 'anthropic code', 'claude cli'],
    primaryUseCases: ['AI coding', 'terminal AI', 'codebase analysis', 'code generation', 'debugging'],
    keyFeatures: ['terminal integration', 'codebase understanding', 'multi-file editing', 'git integration', 'MCP tools'],
    complexity: 'MODERATE',
    typicalPricingTier: 'PROFESSIONAL',
    estimatedCostPerUser: 20.00,
    hasFreeForever: false,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: false,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'CLI-based AI coding assistant with full codebase understanding',
    websiteUrl: 'https://claude.ai/code',
  },
  {
    name: 'gemini',
    displayName: 'Gemini',
    category: 'AI_ASSISTANTS',
    aliases: ['google gemini', 'gemini ai', 'gemini advanced', 'gemini pro', 'gemini ultra'],
    primaryUseCases: ['AI chat', 'search', 'writing', 'coding', 'analysis', 'workspace integration'],
    keyFeatures: ['multimodal', 'Google integration', 'workspace integration', 'deep research', 'gems'],
    complexity: 'SIMPLE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 20.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH', 'ESTABLISHED'],
    bestForTechSavviness: ['NEWBIE', 'DECENT', 'NINJA'],
    soc2: true,
    hipaa: true,
    gdpr: true,
    euDataResidency: true,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'Gemini 2.0 with deep research and workspace integration',
    websiteUrl: 'https://gemini.google.com',
  },
  {
    name: 'perplexity',
    displayName: 'Perplexity',
    category: 'AI_ASSISTANTS',
    aliases: ['perplexity ai', 'perplexity pro', 'perplexity.ai'],
    primaryUseCases: ['AI search', 'research', 'fact-checking', 'writing', 'analysis'],
    keyFeatures: ['real-time search', 'citations', 'deep research', 'spaces', 'collections'],
    complexity: 'SIMPLE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 20.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM', 'LARGE'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH', 'ESTABLISHED'],
    bestForTechSavviness: ['NEWBIE', 'DECENT', 'NINJA'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: false,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI-powered search with real-time citations and deep research',
    websiteUrl: 'https://perplexity.ai',
  },
  {
    name: 'copilot',
    displayName: 'GitHub Copilot',
    category: 'AI_ASSISTANTS',
    aliases: ['github copilot', 'copilot ai', 'copilot workspace'],
    primaryUseCases: ['code completion', 'AI coding', 'code generation', 'code review'],
    keyFeatures: ['inline completion', 'chat', 'code explanation', 'test generation', 'workspace'],
    complexity: 'MODERATE',
    typicalPricingTier: 'PROFESSIONAL',
    estimatedCostPerUser: 19.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH', 'ESTABLISHED'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: true,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI pair programmer with Copilot Workspace for full-stack coding',
    websiteUrl: 'https://github.com/features/copilot',
  },
  {
    name: 'windsurf',
    displayName: 'Windsurf',
    category: 'AI_ASSISTANTS',
    aliases: ['windsurf editor', 'codeium windsurf', 'windsurf ide'],
    primaryUseCases: ['AI coding', 'code editing', 'agentic development', 'code generation'],
    keyFeatures: ['cascade agent', 'flows', 'inline editing', 'codebase understanding', 'multi-file'],
    complexity: 'MODERATE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 15.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: false,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'Agentic AI editor with Cascade for autonomous coding flows',
    websiteUrl: 'https://codeium.com/windsurf',
  },
  {
    name: 'v0',
    displayName: 'v0 by Vercel',
    category: 'AI_ASSISTANTS',
    aliases: ['v0', 'v0.dev', 'vercel v0'],
    primaryUseCases: ['UI generation', 'frontend coding', 'component generation', 'prototyping'],
    keyFeatures: ['React generation', 'Tailwind CSS', 'shadcn/ui', 'instant preview', 'export code'],
    complexity: 'SIMPLE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 20.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH'],
    bestForTechSavviness: ['NEWBIE', 'DECENT', 'NINJA'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: false,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI-powered UI generation with React and Tailwind',
    websiteUrl: 'https://v0.dev',
  },
  {
    name: 'bolt',
    displayName: 'Bolt.new',
    category: 'AI_ASSISTANTS',
    aliases: ['bolt', 'bolt.new', 'stackblitz bolt'],
    primaryUseCases: ['full-stack generation', 'app prototyping', 'rapid development', 'deployment'],
    keyFeatures: ['full-stack AI', 'instant deploy', 'npm packages', 'database setup', 'WebContainers'],
    complexity: 'SIMPLE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 20.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED'],
    bestForTechSavviness: ['NEWBIE', 'DECENT', 'NINJA'],
    soc2: false,
    hipaa: false,
    gdpr: true,
    euDataResidency: false,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI full-stack app generation with instant deployment',
    websiteUrl: 'https://bolt.new',
  },
  {
    name: 'replit-agent',
    displayName: 'Replit Agent',
    category: 'AI_ASSISTANTS',
    aliases: ['replit', 'replit ai', 'replit ghostwriter'],
    primaryUseCases: ['AI coding', 'app building', 'deployment', 'collaboration'],
    keyFeatures: ['agent mode', 'instant deploy', 'multiplayer', 'database', 'hosting'],
    complexity: 'SIMPLE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 25.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH'],
    bestForTechSavviness: ['NEWBIE', 'DECENT', 'NINJA'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: false,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI agent that builds and deploys full applications',
    websiteUrl: 'https://replit.com',
  },
  {
    name: 'lovable',
    displayName: 'Lovable',
    category: 'AI_ASSISTANTS',
    aliases: ['lovable.dev', 'gptengineer', 'gpt engineer'],
    primaryUseCases: ['full-stack generation', 'app building', 'UI generation', 'rapid prototyping'],
    keyFeatures: ['full-stack AI', 'Supabase integration', 'GitHub sync', 'instant preview', 'deploy'],
    complexity: 'SIMPLE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 20.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED'],
    bestForTechSavviness: ['NEWBIE', 'DECENT'],
    soc2: false,
    hipaa: false,
    gdpr: true,
    euDataResidency: false,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI software engineer that builds full-stack apps from prompts',
    websiteUrl: 'https://lovable.dev',
  },
  {
    name: 'codeium',
    displayName: 'Codeium',
    category: 'AI_ASSISTANTS',
    aliases: ['codeium ai'],
    primaryUseCases: ['code completion', 'AI coding', 'code search', 'chat'],
    keyFeatures: ['autocomplete', 'chat', 'search', 'IDE plugins', 'enterprise deployment'],
    complexity: 'SIMPLE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 12.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM', 'LARGE'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH', 'ESTABLISHED'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: false,
    selfHosted: true,
    airGapped: true,
    hasAiFeatures: true,
    aiFeatureDescription: 'Free AI code completion with enterprise self-hosted option',
    websiteUrl: 'https://codeium.com',
  },

  // ANALYTICS (4)
  {
    name: 'amplitude',
    displayName: 'Amplitude',
    category: 'ANALYTICS',
    aliases: ['amplitude.com'],
    primaryUseCases: ['product analytics', 'user behavior', 'experimentation'],
    keyFeatures: ['event tracking', 'funnels', 'cohorts', 'A/B testing', 'notebooks'],
    complexity: 'ADVANCED',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 49.00,
    hasFreeForever: true,
    bestForTeamSize: ['SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE'],
    bestForStage: ['EARLY_SEED', 'GROWTH', 'ESTABLISHED'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    soc2: true,
    hipaa: true,
    gdpr: true,
    euDataResidency: true,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI-powered insights and recommendations',
    websiteUrl: 'https://amplitude.com',
  },
  {
    name: 'mixpanel',
    displayName: 'Mixpanel',
    category: 'ANALYTICS',
    aliases: ['mixpanel.com'],
    primaryUseCases: ['product analytics', 'user tracking', 'retention analysis'],
    keyFeatures: ['events', 'funnels', 'flows', 'retention', 'reports'],
    complexity: 'ADVANCED',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 28.00,
    hasFreeForever: true,
    bestForTeamSize: ['SMALL', 'MEDIUM', 'LARGE'],
    bestForStage: ['EARLY_SEED', 'GROWTH', 'ESTABLISHED'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    soc2: true,
    hipaa: true,
    gdpr: true,
    euDataResidency: true,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'Spark AI for natural language queries',
    websiteUrl: 'https://mixpanel.com',
  },
  {
    name: 'posthog',
    displayName: 'PostHog',
    category: 'ANALYTICS',
    aliases: ['posthog.com'],
    primaryUseCases: ['product analytics', 'session replay', 'feature flags', 'A/B testing'],
    keyFeatures: ['events', 'funnels', 'recordings', 'feature flags', 'surveys'],
    complexity: 'MODERATE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 0,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM', 'LARGE'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    soc2: true,
    hipaa: true,
    gdpr: true,
    euDataResidency: true,
    selfHosted: true,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI-powered product assistant Max',
    websiteUrl: 'https://posthog.com',
  },
  {
    name: 'hotjar',
    displayName: 'Hotjar',
    category: 'ANALYTICS',
    aliases: ['hotjar.com'],
    primaryUseCases: ['heatmaps', 'session recordings', 'surveys', 'feedback'],
    keyFeatures: ['heatmaps', 'recordings', 'surveys', 'feedback widgets', 'funnels'],
    complexity: 'SIMPLE',
    typicalPricingTier: 'FREEMIUM',
    estimatedCostPerUser: 32.00,
    hasFreeForever: true,
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM', 'LARGE'],
    bestForStage: ['PRE_SEED', 'EARLY_SEED', 'GROWTH', 'ESTABLISHED'],
    bestForTechSavviness: ['NEWBIE', 'DECENT', 'NINJA'],
    soc2: true,
    hipaa: false,
    gdpr: true,
    euDataResidency: true,
    selfHosted: false,
    airGapped: false,
    hasAiFeatures: true,
    aiFeatureDescription: 'AI survey analysis and insights',
    websiteUrl: 'https://hotjar.com',
  },
];

// ============================================
// REDUNDANCY DATA
// ============================================

const redundancies = [
  // Project Management overlaps
  { toolA: 'jira', toolB: 'linear', overlappingUseCases: ['issue tracking', 'sprint planning'], overlappingFeatures: ['kanban boards', 'roadmaps'], redundancyStrength: 'FULL', recommendationHint: 'CONTEXT_DEPENDENT', notes: 'Linear is simpler, Jira has more enterprise features' },
  { toolA: 'jira', toolB: 'asana', overlappingUseCases: ['project management', 'task tracking'], overlappingFeatures: ['boards', 'timelines'], redundancyStrength: 'PARTIAL', recommendationHint: 'CONTEXT_DEPENDENT' },
  { toolA: 'linear', toolB: 'shortcut', overlappingUseCases: ['issue tracking', 'project planning'], overlappingFeatures: ['keyboard shortcuts', 'roadmaps'], redundancyStrength: 'FULL', recommendationHint: 'PREFER_A' },
  { toolA: 'asana', toolB: 'monday', overlappingUseCases: ['project management', 'workflow automation'], overlappingFeatures: ['boards', 'automations'], redundancyStrength: 'FULL', recommendationHint: 'CONTEXT_DEPENDENT' },
  { toolA: 'trello', toolB: 'asana', overlappingUseCases: ['task management', 'visual boards'], overlappingFeatures: ['kanban boards'], redundancyStrength: 'PARTIAL', recommendationHint: 'PREFER_B' },
  { toolA: 'clickup', toolB: 'notion', overlappingUseCases: ['project management', 'documentation'], overlappingFeatures: ['docs', 'tasks'], redundancyStrength: 'PARTIAL', recommendationHint: 'CONTEXT_DEPENDENT' },
  { toolA: 'clickup', toolB: 'asana', overlappingUseCases: ['project management', 'task tracking'], overlappingFeatures: ['goals', 'timelines'], redundancyStrength: 'FULL', recommendationHint: 'CONTEXT_DEPENDENT' },

  // Documentation overlaps
  { toolA: 'notion', toolB: 'confluence', overlappingUseCases: ['documentation', 'wikis'], overlappingFeatures: ['pages', 'templates'], redundancyStrength: 'FULL', recommendationHint: 'CONTEXT_DEPENDENT', notes: 'Notion is more flexible, Confluence integrates with Jira' },
  { toolA: 'notion', toolB: 'coda', overlappingUseCases: ['documentation', 'databases'], overlappingFeatures: ['blocks', 'formulas'], redundancyStrength: 'FULL', recommendationHint: 'PREFER_A' },
  { toolA: 'notion', toolB: 'slite', overlappingUseCases: ['team wiki', 'documentation'], overlappingFeatures: ['channels', 'search'], redundancyStrength: 'FULL', recommendationHint: 'PREFER_A' },
  { toolA: 'gitbook', toolB: 'notion', overlappingUseCases: ['documentation'], overlappingFeatures: ['pages', 'versioning'], redundancyStrength: 'PARTIAL', recommendationHint: 'CONTEXT_DEPENDENT', notes: 'GitBook better for public docs' },

  // Communication overlaps
  { toolA: 'slack', toolB: 'discord', overlappingUseCases: ['team messaging', 'channels'], overlappingFeatures: ['channels', 'threads'], redundancyStrength: 'FULL', recommendationHint: 'PREFER_A', notes: 'Slack has better enterprise features' },
  { toolA: 'slack', toolB: 'teams', overlappingUseCases: ['team messaging', 'video calls'], overlappingFeatures: ['channels', 'apps'], redundancyStrength: 'FULL', recommendationHint: 'CONTEXT_DEPENDENT' },
  { toolA: 'zoom', toolB: 'teams', overlappingUseCases: ['video conferencing', 'screen sharing'], overlappingFeatures: ['meetings', 'recording'], redundancyStrength: 'PARTIAL', recommendationHint: 'CONTEXT_DEPENDENT' },

  // Meeting tools overlaps
  { toolA: 'fireflies', toolB: 'otter', overlappingUseCases: ['meeting transcription', 'note-taking'], overlappingFeatures: ['transcription', 'summaries'], redundancyStrength: 'FULL', recommendationHint: 'CONTEXT_DEPENDENT' },
  { toolA: 'fireflies', toolB: 'grain', overlappingUseCases: ['meeting recording', 'transcription'], overlappingFeatures: ['AI summaries', 'highlights'], redundancyStrength: 'FULL', recommendationHint: 'CONTEXT_DEPENDENT' },
  { toolA: 'fathom', toolB: 'tldv', overlappingUseCases: ['meeting recording', 'summaries'], overlappingFeatures: ['auto-recording', 'clips'], redundancyStrength: 'FULL', recommendationHint: 'CONTEXT_DEPENDENT' },
  { toolA: 'otter', toolB: 'grain', overlappingUseCases: ['meeting transcription'], overlappingFeatures: ['transcription', 'search'], redundancyStrength: 'FULL', recommendationHint: 'CONTEXT_DEPENDENT' },

  // Design overlaps
  { toolA: 'miro', toolB: 'figjam', overlappingUseCases: ['whiteboarding', 'brainstorming'], overlappingFeatures: ['sticky notes', 'voting'], redundancyStrength: 'FULL', recommendationHint: 'CONTEXT_DEPENDENT', notes: 'FigJam integrates with Figma' },
  { toolA: 'figma', toolB: 'canva', overlappingUseCases: ['graphic design'], overlappingFeatures: ['templates'], redundancyStrength: 'NICHE', recommendationHint: 'CONTEXT_DEPENDENT', notes: 'Different use cases - Figma for UI, Canva for marketing' },

  // Automation overlaps
  { toolA: 'zapier', toolB: 'make', overlappingUseCases: ['workflow automation', 'integration'], overlappingFeatures: ['visual builder', 'triggers'], redundancyStrength: 'FULL', recommendationHint: 'CONTEXT_DEPENDENT', notes: 'Make is more powerful, Zapier is simpler' },
  { toolA: 'n8n', toolB: 'make', overlappingUseCases: ['workflow automation', 'integration'], overlappingFeatures: ['visual builder', 'code nodes'], redundancyStrength: 'FULL', recommendationHint: 'CONTEXT_DEPENDENT', notes: 'n8n is self-hostable' },
  { toolA: 'pipedream', toolB: 'n8n', overlappingUseCases: ['workflow automation', 'API integration'], overlappingFeatures: ['code-first', 'triggers'], redundancyStrength: 'PARTIAL', recommendationHint: 'CONTEXT_DEPENDENT' },

  // AI Assistants overlaps
  { toolA: 'chatgpt', toolB: 'claude', overlappingUseCases: ['AI chat', 'writing', 'coding'], overlappingFeatures: ['conversation', 'analysis'], redundancyStrength: 'FULL', recommendationHint: 'CONTEXT_DEPENDENT', notes: 'Different strengths - Claude for long docs, GPT for plugins' },
  { toolA: 'chatgpt', toolB: 'gemini', overlappingUseCases: ['AI chat', 'writing', 'analysis'], overlappingFeatures: ['conversation', 'multimodal'], redundancyStrength: 'FULL', recommendationHint: 'CONTEXT_DEPENDENT', notes: 'Gemini better for Google Workspace users' },
  { toolA: 'claude', toolB: 'gemini', overlappingUseCases: ['AI chat', 'writing', 'analysis'], overlappingFeatures: ['conversation', 'long context'], redundancyStrength: 'FULL', recommendationHint: 'CONTEXT_DEPENDENT' },
  { toolA: 'chatgpt', toolB: 'perplexity', overlappingUseCases: ['AI chat', 'research'], overlappingFeatures: ['conversation'], redundancyStrength: 'PARTIAL', recommendationHint: 'CONTEXT_DEPENDENT', notes: 'Perplexity better for research with citations' },
  { toolA: 'copilot', toolB: 'codeium', overlappingUseCases: ['code completion', 'AI coding'], overlappingFeatures: ['autocomplete', 'chat'], redundancyStrength: 'FULL', recommendationHint: 'CONTEXT_DEPENDENT', notes: 'Codeium is free' },
  { toolA: 'cursor', toolB: 'copilot', overlappingUseCases: ['AI coding', 'code completion'], overlappingFeatures: ['AI chat', 'autocomplete'], redundancyStrength: 'PARTIAL', recommendationHint: 'CONTEXT_DEPENDENT', notes: 'Cursor is a full editor, Copilot is a plugin' },
  { toolA: 'cursor', toolB: 'windsurf', overlappingUseCases: ['AI coding', 'code editing'], overlappingFeatures: ['AI chat', 'multi-file editing'], redundancyStrength: 'FULL', recommendationHint: 'CONTEXT_DEPENDENT', notes: 'Both are AI-first code editors' },
  { toolA: 'cursor', toolB: 'claude-code', overlappingUseCases: ['AI coding', 'codebase understanding'], overlappingFeatures: ['AI chat', 'multi-file editing'], redundancyStrength: 'PARTIAL', recommendationHint: 'CONTEXT_DEPENDENT', notes: 'Claude Code is terminal-based, Cursor is GUI' },
  { toolA: 'bolt', toolB: 'lovable', overlappingUseCases: ['full-stack generation', 'app building'], overlappingFeatures: ['AI generation', 'instant deploy'], redundancyStrength: 'FULL', recommendationHint: 'CONTEXT_DEPENDENT', notes: 'Both are AI app builders' },
  { toolA: 'bolt', toolB: 'replit-agent', overlappingUseCases: ['app building', 'deployment'], overlappingFeatures: ['AI generation', 'hosting'], redundancyStrength: 'FULL', recommendationHint: 'CONTEXT_DEPENDENT', notes: 'Replit offers more collaboration features' },
  { toolA: 'v0', toolB: 'bolt', overlappingUseCases: ['UI generation', 'frontend coding'], overlappingFeatures: ['React generation', 'preview'], redundancyStrength: 'PARTIAL', recommendationHint: 'CONTEXT_DEPENDENT', notes: 'v0 is UI-focused, Bolt is full-stack' },
  { toolA: 'windsurf', toolB: 'codeium', overlappingUseCases: ['AI coding', 'code completion'], overlappingFeatures: ['autocomplete', 'chat'], redundancyStrength: 'PARTIAL', recommendationHint: 'PREFER_A', notes: 'Windsurf is the full editor from Codeium' },

  // Development overlaps
  { toolA: 'github', toolB: 'gitlab', overlappingUseCases: ['version control', 'CI/CD'], overlappingFeatures: ['repos', 'merge requests'], redundancyStrength: 'FULL', recommendationHint: 'CONTEXT_DEPENDENT', notes: 'GitLab has built-in CI/CD, GitHub has larger ecosystem' },
  { toolA: 'vercel', toolB: 'railway', overlappingUseCases: ['app hosting', 'deployment'], overlappingFeatures: ['preview deployments', 'CI/CD'], redundancyStrength: 'PARTIAL', recommendationHint: 'CONTEXT_DEPENDENT', notes: 'Vercel for frontend, Railway for full-stack' },

  // Analytics overlaps
  { toolA: 'amplitude', toolB: 'mixpanel', overlappingUseCases: ['product analytics', 'user tracking'], overlappingFeatures: ['funnels', 'retention'], redundancyStrength: 'FULL', recommendationHint: 'CONTEXT_DEPENDENT' },
  { toolA: 'posthog', toolB: 'amplitude', overlappingUseCases: ['product analytics'], overlappingFeatures: ['events', 'funnels'], redundancyStrength: 'FULL', recommendationHint: 'CONTEXT_DEPENDENT', notes: 'PostHog is open-source' },
  { toolA: 'posthog', toolB: 'hotjar', overlappingUseCases: ['session recordings'], overlappingFeatures: ['recordings', 'heatmaps'], redundancyStrength: 'PARTIAL', recommendationHint: 'CONTEXT_DEPENDENT' },
];

// ============================================
// REPLACEMENT DATA
// ============================================

const replacements = [
  // Cost savings replacements
  { from: 'jira', to: 'linear', reasonType: 'COST_SAVINGS', reasonText: 'Linear offers similar functionality at lower cost for smaller teams', context: 'Startups and small teams', conditions: { teamSize: ['SOLO', 'SMALL'], costSensitivity: ['PRICE_FIRST'] } },
  { from: 'confluence', to: 'notion', reasonType: 'COST_SAVINGS', reasonText: 'Notion provides wiki and documentation at lower cost', context: 'Teams not heavily invested in Atlassian ecosystem' },
  { from: 'asana', to: 'clickup', reasonType: 'COST_SAVINGS', reasonText: 'ClickUp offers more features in free tier', context: 'Budget-conscious teams', conditions: { costSensitivity: ['PRICE_FIRST'] } },
  { from: 'amplitude', to: 'posthog', reasonType: 'COST_SAVINGS', reasonText: 'PostHog offers generous free tier and self-hosting option', context: 'Startups needing analytics', conditions: { costSensitivity: ['PRICE_FIRST', 'BALANCED'] } },
  { from: 'copilot', to: 'codeium', reasonType: 'COST_SAVINGS', reasonText: 'Codeium offers free AI code completion', context: 'Individual developers or bootstrap startups', conditions: { costSensitivity: ['PRICE_FIRST'] } },

  // Feature superset replacements
  { from: 'trello', to: 'notion', reasonType: 'FEATURE_SUPERSET', reasonText: 'Notion can do everything Trello does plus documentation', context: 'Teams wanting to consolidate tools' },
  { from: 'trello', to: 'linear', reasonType: 'FEATURE_SUPERSET', reasonText: 'Linear offers more powerful project management features', context: 'Product teams wanting advanced features' },
  { from: 'slite', to: 'notion', reasonType: 'FEATURE_SUPERSET', reasonText: 'Notion offers more powerful database and integration features', context: 'Teams needing more than basic wiki' },
  { from: 'basecamp', to: 'clickup', reasonType: 'FEATURE_SUPERSET', reasonText: 'ClickUp offers more customization and features', context: 'Teams needing more flexibility' },

  // Better integration replacements
  { from: 'confluence', to: 'notion', reasonType: 'BETTER_INTEGRATION', reasonText: 'Notion has better API and integration ecosystem for non-Atlassian stacks', context: 'Teams not using Jira', conditions: { preferAiNative: true } },
  { from: 'discord', to: 'slack', reasonType: 'BETTER_INTEGRATION', reasonText: 'Slack has superior integration with business tools', context: 'Professional teams needing integrations' },

  // Simpler UX replacements
  { from: 'jira', to: 'linear', reasonType: 'SIMPLER_UX', reasonText: 'Linear has a cleaner, faster interface', context: 'Teams frustrated with Jira complexity', conditions: { techSavviness: ['NEWBIE', 'DECENT'] } },
  { from: 'clickup', to: 'asana', reasonType: 'SIMPLER_UX', reasonText: 'Asana has a more intuitive interface', context: 'Teams finding ClickUp overwhelming', conditions: { techSavviness: ['NEWBIE'] } },
  { from: 'make', to: 'zapier', reasonType: 'SIMPLER_UX', reasonText: 'Zapier has simpler setup for basic automations', context: 'Non-technical users', conditions: { techSavviness: ['NEWBIE'] } },
  { from: 'n8n', to: 'zapier', reasonType: 'SIMPLER_UX', reasonText: 'Zapier requires no technical setup', context: 'Teams without developers', conditions: { techSavviness: ['NEWBIE'] } },

  // Consolidation replacements
  { from: 'miro', to: 'figjam', reasonType: 'CONSOLIDATION', reasonText: 'FigJam integrates seamlessly with Figma', context: 'Teams already using Figma' },
  { from: 'otter', to: 'fireflies', reasonType: 'CONSOLIDATION', reasonText: 'Fireflies has better CRM and tool integrations', context: 'Sales and customer success teams' },
  { from: 'zoom', to: 'teams', reasonType: 'CONSOLIDATION', reasonText: 'Teams combines video with chat and collaboration', context: 'Microsoft 365 users' },
  { from: 'hotjar', to: 'posthog', reasonType: 'CONSOLIDATION', reasonText: 'PostHog combines analytics with session replay', context: 'Teams wanting unified analytics' },

  // Compliance replacements
  { from: 'notion', to: 'confluence', reasonType: 'COMPLIANCE', reasonText: 'Confluence offers better compliance features', context: 'Enterprises with strict compliance needs', conditions: { requiresCompliance: ['SOC 2', 'HIPAA'] } },
  { from: 'discord', to: 'slack', reasonType: 'COMPLIANCE', reasonText: 'Slack offers enterprise security and compliance', context: 'Regulated industries', conditions: { requiresCompliance: ['SOC 2', 'HIPAA'] } },
  { from: 'railway', to: 'vercel', reasonType: 'COMPLIANCE', reasonText: 'Vercel offers HIPAA compliance option', context: 'Healthcare applications', conditions: { requiresCompliance: ['HIPAA'] } },

  // AI-native replacements
  { from: 'vscode', to: 'cursor', reasonType: 'AI_NATIVE', reasonText: 'Cursor is built AI-first with superior code understanding', context: 'Developers wanting maximum AI assistance', conditions: { preferAiNative: true } },
  { from: 'vscode', to: 'windsurf', reasonType: 'AI_NATIVE', reasonText: 'Windsurf offers agentic AI coding with Cascade', context: 'Developers wanting autonomous coding assistance', conditions: { preferAiNative: true } },
  { from: 'copilot', to: 'cursor', reasonType: 'AI_NATIVE', reasonText: 'Cursor provides deeper codebase understanding than Copilot plugin', context: 'Developers wanting AI-first experience', conditions: { preferAiNative: true } },
  { from: 'chatgpt', to: 'perplexity', reasonType: 'AI_NATIVE', reasonText: 'Perplexity provides citations and real-time search', context: 'Research-heavy workflows', conditions: { preferAiNative: true } },
  { from: 'chatgpt', to: 'claude', reasonType: 'AI_NATIVE', reasonText: 'Claude excels at long document analysis and coding', context: 'Teams working with long documents or code', conditions: { preferAiNative: true } },
];

// ============================================
// BUNDLE DATA
// ============================================

const bundles = [
  // Mono-Stack Scenarios
  {
    name: 'Notion Everything Stack',
    description: 'Use Notion as your single source of truth for docs, project management, and wikis',
    toolNames: ['notion', 'slack', 'figma'],
    toolRoles: { 'notion': 'Central hub for docs, projects, and wikis', 'slack': 'Communication', 'figma': 'Design' },
    primaryUseCasesCovered: ['documentation', 'project management', 'wikis', 'communication', 'design'],
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED'],
    bestForTechSavviness: ['NEWBIE', 'DECENT', 'NINJA'],
    anchorToolName: 'notion',
    scenarioType: 'MONO_STACK',
    estimatedMonthlyCost: 31,
  },
  {
    name: 'ClickUp All-in-One',
    description: 'ClickUp as the everything app with minimal external dependencies',
    toolNames: ['clickup', 'slack', 'github'],
    toolRoles: { 'clickup': 'Projects, docs, goals, and time tracking', 'slack': 'Communication', 'github': 'Code' },
    primaryUseCasesCovered: ['project management', 'documentation', 'goals', 'time tracking', 'communication'],
    bestForTeamSize: ['SMALL', 'MEDIUM'],
    bestForStage: ['PRE_SEED', 'EARLY_SEED', 'GROWTH'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    anchorToolName: 'clickup',
    scenarioType: 'MONO_STACK',
    estimatedMonthlyCost: 23,
  },
  {
    name: 'Linear-Centric Dev Shop',
    description: 'Linear as the hub for engineering teams with minimal tool sprawl',
    toolNames: ['linear', 'notion', 'slack', 'github', 'cursor'],
    toolRoles: { 'linear': 'Issue tracking and sprints', 'notion': 'Documentation', 'slack': 'Communication', 'github': 'Code', 'cursor': 'AI coding' },
    primaryUseCasesCovered: ['issue tracking', 'sprint planning', 'documentation', 'code hosting', 'AI coding'],
    bestForTeamSize: ['SMALL', 'MEDIUM'],
    bestForStage: ['PRE_SEED', 'EARLY_SEED', 'GROWTH'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    anchorToolName: 'linear',
    scenarioType: 'MONO_STACK',
    estimatedMonthlyCost: 48.75,
  },

  // Native Integrator Scenarios
  {
    name: 'Atlassian Stack',
    description: 'Deep integration between Jira, Confluence, and Trello for enterprise workflows',
    toolNames: ['jira', 'confluence', 'slack', 'figma', 'github'],
    toolRoles: { 'jira': 'Issue tracking', 'confluence': 'Documentation', 'slack': 'Communication', 'figma': 'Design', 'github': 'Code' },
    primaryUseCasesCovered: ['issue tracking', 'documentation', 'design', 'code hosting', 'communication'],
    bestForTeamSize: ['MEDIUM', 'LARGE', 'ENTERPRISE'],
    bestForStage: ['GROWTH', 'ESTABLISHED'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    anchorToolName: 'jira',
    scenarioType: 'NATIVE_INTEGRATOR',
    estimatedMonthlyCost: 45.95,
  },
  {
    name: 'Modern PM Stack',
    description: 'Best-of-breed modern tools with native integrations',
    toolNames: ['linear', 'notion', 'slack', 'figma', 'github', 'vercel'],
    toolRoles: { 'linear': 'Issue tracking', 'notion': 'Documentation', 'slack': 'Communication', 'figma': 'Design', 'github': 'Code', 'vercel': 'Deployment' },
    primaryUseCasesCovered: ['issue tracking', 'documentation', 'design', 'code hosting', 'deployment', 'communication'],
    bestForTeamSize: ['SMALL', 'MEDIUM'],
    bestForStage: ['PRE_SEED', 'EARLY_SEED', 'GROWTH'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    anchorToolName: 'linear',
    scenarioType: 'NATIVE_INTEGRATOR',
    estimatedMonthlyCost: 63.75,
  },
  {
    name: 'Startup PM Stack',
    description: 'Cost-effective integrated stack for startups',
    toolNames: ['asana', 'notion', 'slack', 'figma', 'github'],
    toolRoles: { 'asana': 'Project management', 'notion': 'Documentation', 'slack': 'Communication', 'figma': 'Design', 'github': 'Code' },
    primaryUseCasesCovered: ['project management', 'documentation', 'design', 'code hosting', 'communication'],
    bestForTeamSize: ['SMALL', 'MEDIUM'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED'],
    bestForTechSavviness: ['NEWBIE', 'DECENT', 'NINJA'],
    anchorToolName: 'notion',
    scenarioType: 'NATIVE_INTEGRATOR',
    estimatedMonthlyCost: 45.74,
  },

  // Agentic Lean Scenarios
  {
    name: 'AI-First Dev Stack',
    description: 'Maximum automation with AI-native tools',
    toolNames: ['cursor', 'linear', 'notion', 'slack', 'fireflies', 'claude'],
    toolRoles: { 'cursor': 'AI coding', 'linear': 'AI-powered issues', 'notion': 'AI documentation', 'slack': 'AI search', 'fireflies': 'AI meeting notes', 'claude': 'AI assistant' },
    primaryUseCasesCovered: ['AI coding', 'issue tracking', 'documentation', 'meeting notes', 'AI assistance'],
    bestForTeamSize: ['SOLO', 'SMALL', 'MEDIUM'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED', 'GROWTH'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    anchorToolName: 'cursor',
    scenarioType: 'AGENTIC_LEAN',
    estimatedMonthlyCost: 74.75,
  },
  {
    name: 'Automation-First Stack',
    description: 'Minimal manual work with AI and automation everywhere',
    toolNames: ['height', 'notion', 'slack', 'zapier', 'fireflies', 'chatgpt'],
    toolRoles: { 'height': 'AI project management', 'notion': 'AI documentation', 'slack': 'AI communication', 'zapier': 'Workflow automation', 'fireflies': 'AI meetings', 'chatgpt': 'AI assistant' },
    primaryUseCasesCovered: ['project management', 'documentation', 'automation', 'meeting notes', 'AI assistance'],
    bestForTeamSize: ['SOLO', 'SMALL'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    anchorToolName: 'notion',
    scenarioType: 'AGENTIC_LEAN',
    estimatedMonthlyCost: 85.24,
  },
  {
    name: 'Solo Founder AI Stack',
    description: 'AI assistants for a team of one',
    toolNames: ['notion', 'cursor', 'chatgpt', 'loom', 'zapier'],
    toolRoles: { 'notion': 'Central workspace', 'cursor': 'AI coding', 'chatgpt': 'AI assistant', 'loom': 'Async communication', 'zapier': 'Automation' },
    primaryUseCasesCovered: ['documentation', 'coding', 'AI assistance', 'async communication', 'automation'],
    bestForTeamSize: ['SOLO'],
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    anchorToolName: 'notion',
    scenarioType: 'AGENTIC_LEAN',
    estimatedMonthlyCost: 68.49,
  },

  // Starter Pack Scenarios
  {
    name: 'Bootstrap Starter',
    description: 'Essential free tools to get started',
    toolNames: ['notion', 'slack', 'github', 'figma'],
    toolRoles: { 'notion': 'Docs and planning', 'slack': 'Communication', 'github': 'Code', 'figma': 'Design' },
    primaryUseCasesCovered: ['documentation', 'communication', 'code hosting', 'design'],
    bestForTeamSize: ['SOLO', 'SMALL'],
    bestForStage: ['BOOTSTRAPPING'],
    bestForTechSavviness: ['NEWBIE', 'DECENT', 'NINJA'],
    anchorToolName: 'notion',
    scenarioType: 'STARTER_PACK',
    estimatedMonthlyCost: 0,
  },
  {
    name: 'Pre-Seed Starter',
    description: 'Affordable stack for pre-seed startups',
    toolNames: ['linear', 'notion', 'slack', 'figma', 'github', 'posthog'],
    toolRoles: { 'linear': 'Issues', 'notion': 'Docs', 'slack': 'Communication', 'figma': 'Design', 'github': 'Code', 'posthog': 'Analytics' },
    primaryUseCasesCovered: ['issue tracking', 'documentation', 'communication', 'design', 'code hosting', 'analytics'],
    bestForTeamSize: ['SMALL'],
    bestForStage: ['PRE_SEED', 'EARLY_SEED'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    anchorToolName: 'linear',
    scenarioType: 'STARTER_PACK',
    estimatedMonthlyCost: 23.75,
  },
];

// ============================================
// PHASE RECOMMENDATIONS
// ============================================

const phaseRecommendations = [
  // IDEATION
  { phase: 'IDEATION', toolName: 'notion', role: 'Brainstorming and idea capture', techSavviness: ['NEWBIE', 'DECENT', 'NINJA'], note: 'Use databases for idea tracking', displayOrder: 1 },
  { phase: 'IDEATION', toolName: 'miro', role: 'Visual brainstorming and workshops', techSavviness: ['NEWBIE', 'DECENT', 'NINJA'], displayOrder: 2 },
  { phase: 'IDEATION', toolName: 'figjam', role: 'Quick whiteboarding sessions', techSavviness: ['NEWBIE', 'DECENT', 'NINJA'], displayOrder: 3 },
  { phase: 'IDEATION', toolName: 'chatgpt', role: 'AI ideation partner', techSavviness: ['NEWBIE', 'DECENT', 'NINJA'], displayOrder: 4 },
  { phase: 'IDEATION', toolName: 'claude', role: 'AI research and analysis', techSavviness: ['DECENT', 'NINJA'], displayOrder: 5 },

  // PLANNING
  { phase: 'PLANNING', toolName: 'linear', role: 'Sprint planning and issue creation', techSavviness: ['DECENT', 'NINJA'], displayOrder: 1 },
  { phase: 'PLANNING', toolName: 'notion', role: 'PRDs and specifications', techSavviness: ['NEWBIE', 'DECENT', 'NINJA'], displayOrder: 2 },
  { phase: 'PLANNING', toolName: 'jira', role: 'Enterprise project planning', techSavviness: ['DECENT', 'NINJA'], displayOrder: 3 },
  { phase: 'PLANNING', toolName: 'asana', role: 'Task planning and timelines', techSavviness: ['NEWBIE', 'DECENT', 'NINJA'], displayOrder: 4 },
  { phase: 'PLANNING', toolName: 'height', role: 'AI-assisted task breakdown', techSavviness: ['DECENT', 'NINJA'], displayOrder: 5 },

  // EXECUTION
  { phase: 'EXECUTION', toolName: 'cursor', role: 'AI-powered development', techSavviness: ['DECENT', 'NINJA'], displayOrder: 1 },
  { phase: 'EXECUTION', toolName: 'github', role: 'Version control and CI/CD', techSavviness: ['DECENT', 'NINJA'], displayOrder: 2 },
  { phase: 'EXECUTION', toolName: 'figma', role: 'UI/UX design and prototyping', techSavviness: ['NEWBIE', 'DECENT', 'NINJA'], displayOrder: 3 },
  { phase: 'EXECUTION', toolName: 'vercel', role: 'Deployment and hosting', techSavviness: ['DECENT', 'NINJA'], displayOrder: 4 },
  { phase: 'EXECUTION', toolName: 'copilot', role: 'Code completion assistant', techSavviness: ['DECENT', 'NINJA'], displayOrder: 5 },

  // REVIEW
  { phase: 'REVIEW', toolName: 'fireflies', role: 'Meeting transcription and action items', techSavviness: ['NEWBIE', 'DECENT', 'NINJA'], displayOrder: 1 },
  { phase: 'REVIEW', toolName: 'loom', role: 'Async video updates and demos', techSavviness: ['NEWBIE', 'DECENT', 'NINJA'], displayOrder: 2 },
  { phase: 'REVIEW', toolName: 'slack', role: 'Feedback collection and discussions', techSavviness: ['NEWBIE', 'DECENT', 'NINJA'], displayOrder: 3 },
  { phase: 'REVIEW', toolName: 'notion', role: 'Review documentation and notes', techSavviness: ['NEWBIE', 'DECENT', 'NINJA'], displayOrder: 4 },
  { phase: 'REVIEW', toolName: 'zoom', role: 'Live demo calls and reviews', techSavviness: ['NEWBIE', 'DECENT', 'NINJA'], displayOrder: 5 },

  // ITERATE
  { phase: 'ITERATE', toolName: 'posthog', role: 'Product analytics and insights', techSavviness: ['DECENT', 'NINJA'], displayOrder: 1 },
  { phase: 'ITERATE', toolName: 'amplitude', role: 'Advanced behavior analytics', techSavviness: ['DECENT', 'NINJA'], displayOrder: 2 },
  { phase: 'ITERATE', toolName: 'hotjar', role: 'User recordings and heatmaps', techSavviness: ['NEWBIE', 'DECENT', 'NINJA'], displayOrder: 3 },
  { phase: 'ITERATE', toolName: 'linear', role: 'Feedback to backlog loop', techSavviness: ['DECENT', 'NINJA'], displayOrder: 4 },
  { phase: 'ITERATE', toolName: 'notion', role: 'Iteration planning docs', techSavviness: ['NEWBIE', 'DECENT', 'NINJA'], displayOrder: 5 },
];

// ============================================
// SEED FUNCTION
// ============================================

async function seed() {
  console.log('🌱 Starting database seed...\n');

  try {
    // Clear existing data
    console.log('🧹 Clearing existing data...');
    await prisma.phaseToolRecommendation.deleteMany();
    await prisma.bundleTool.deleteMany();
    await prisma.toolBundle.deleteMany();
    await prisma.toolReplacement.deleteMany();
    await prisma.toolRedundancy.deleteMany();
    await prisma.toolIntegration.deleteMany();
    await prisma.tool.deleteMany();
    console.log('✅ Cleared existing data\n');

    // Seed tools
    console.log('🔧 Seeding tools...');
    const toolMap = new Map<string, string>();

    for (const tool of tools) {
      const created = await prisma.tool.create({
        data: tool as any,
      });
      toolMap.set(tool.name, created.id);
      console.log(`  ✓ ${tool.displayName}`);
    }
    console.log(`✅ Seeded ${tools.length} tools\n`);

    // Seed redundancies
    console.log('🔄 Seeding redundancies...');
    let redundancyCount = 0;
    for (const r of redundancies) {
      const toolAId = toolMap.get(r.toolA);
      const toolBId = toolMap.get(r.toolB);

      if (toolAId && toolBId) {
        await prisma.toolRedundancy.create({
          data: {
            toolAId,
            toolBId,
            overlappingUseCases: r.overlappingUseCases,
            overlappingFeatures: r.overlappingFeatures,
            redundancyStrength: r.redundancyStrength as any,
            recommendationHint: r.recommendationHint as any,
            notes: r.notes || null,
          },
        });
        redundancyCount++;
      }
    }
    console.log(`✅ Seeded ${redundancyCount} redundancies\n`);

    // Seed replacements (dedupe by from+to)
    console.log('🔀 Seeding replacements...');
    let replacementCount = 0;
    const seenReplacements = new Set<string>();
    for (const r of replacements) {
      const fromToolId = toolMap.get(r.from);
      const toToolId = toolMap.get(r.to);
      const key = `${r.from}->${r.to}`;

      if (fromToolId && toToolId && !seenReplacements.has(key)) {
        seenReplacements.add(key);
        await prisma.toolReplacement.create({
          data: {
            fromToolId,
            toToolId,
            reasonType: r.reasonType as any,
            reasonText: r.reasonText,
            context: r.context || null,
            conditions: r.conditions || null,
          },
        });
        replacementCount++;
      }
    }
    console.log(`✅ Seeded ${replacementCount} replacements\n`);

    // Seed bundles
    console.log('📦 Seeding bundles...');
    for (const bundle of bundles) {
      const anchorToolId = bundle.anchorToolName ? toolMap.get(bundle.anchorToolName) : null;

      // Convert tool roles to IDs
      const toolRolesWithIds: Record<string, string> = {};
      for (const [name, role] of Object.entries(bundle.toolRoles)) {
        const toolId = toolMap.get(name);
        if (toolId) {
          toolRolesWithIds[toolId] = role;
        }
      }

      const createdBundle = await prisma.toolBundle.create({
        data: {
          name: bundle.name,
          description: bundle.description,
          toolRoles: toolRolesWithIds,
          primaryUseCasesCovered: bundle.primaryUseCasesCovered,
          bestForTeamSize: bundle.bestForTeamSize as any,
          bestForStage: bundle.bestForStage as any,
          bestForTechSavviness: bundle.bestForTechSavviness as any,
          anchorToolId,
          scenarioType: bundle.scenarioType as any,
          estimatedMonthlyCost: bundle.estimatedMonthlyCost,
        },
      });

      // Create bundle-tool associations
      for (const toolName of bundle.toolNames) {
        const toolId = toolMap.get(toolName);
        if (toolId) {
          await prisma.bundleTool.create({
            data: {
              bundleId: createdBundle.id,
              toolId,
              role: bundle.toolRoles[toolName] || null,
            },
          });
        }
      }

      console.log(`  ✓ ${bundle.name}`);
    }
    console.log(`✅ Seeded ${bundles.length} bundles\n`);

    // Seed phase recommendations
    console.log('📋 Seeding phase recommendations...');
    let phaseCount = 0;
    for (const rec of phaseRecommendations) {
      const toolId = toolMap.get(rec.toolName);

      if (toolId) {
        await prisma.phaseToolRecommendation.create({
          data: {
            phase: rec.phase as any,
            toolId,
            role: rec.role,
            techSavviness: rec.techSavviness as any,
            note: rec.note || null,
            displayOrder: rec.displayOrder,
          },
        });
        phaseCount++;
      }
    }
    console.log(`✅ Seeded ${phaseCount} phase recommendations\n`);

    console.log('🎉 Database seeding complete!\n');
    console.log('Summary:');
    console.log(`  • ${tools.length} tools`);
    console.log(`  • ${redundancyCount} redundancy pairs`);
    console.log(`  • ${replacementCount} replacement rules`);
    console.log(`  • ${bundles.length} bundles`);
    console.log(`  • ${phaseCount} phase recommendations`);

  } catch (error) {
    console.error('❌ Error seeding database:', error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

// Run seed
seed()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
