/**
 * Seed data for initial ToolClusters.
 * Hand-curated clusters based on common tool stacks seen in the wild.
 */

export interface SeedCluster {
  name: string;
  description: string;
  synergyStrength: number;
  synergyType: string;
  bestForStage: string[];
  bestForTeamSize: string[];
  bestForTechSavviness: string[];
  confidence: number;
  sourceCount: number;
  sourceTypes: string[];
  biasFlags: string[];
  status: string;
  tools: Array<{ toolName: string; role: string }>;
}

export const seedClusters: SeedCluster[] = [
  {
    name: 'The Indie Dev Stack',
    description: 'Linear + GitHub + Vercel — a tightly integrated dev workflow for small teams shipping fast. Issue tracking flows directly into code via branch automation.',
    synergyStrength: 85,
    synergyType: 'sequential',
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED'],
    bestForTeamSize: ['SOLO', 'SMALL'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    confidence: 78,
    sourceCount: 12,
    sourceTypes: ['youtube_transcript', 'reddit', 'hackernews'],
    biasFlags: [],
    status: 'approved',
    tools: [
      { toolName: 'linear', role: 'issue-tracker' },
      { toolName: 'github', role: 'code-host' },
      { toolName: 'vercel', role: 'deployment' },
    ],
  },
  {
    name: 'Doc-Centric Hub',
    description: 'Notion + Slack + Loom — documentation-first collaboration where async communication reduces meetings. Notion is the single source of truth.',
    synergyStrength: 80,
    synergyType: 'hub-spoke',
    bestForStage: ['PRE_SEED', 'EARLY_SEED', 'GROWTH'],
    bestForTeamSize: ['SMALL', 'MEDIUM'],
    bestForTechSavviness: ['NEWBIE', 'DECENT'],
    confidence: 82,
    sourceCount: 18,
    sourceTypes: ['youtube_transcript', 'reddit', 'product_hunt'],
    biasFlags: [],
    status: 'approved',
    tools: [
      { toolName: 'notion', role: 'hub' },
      { toolName: 'slack', role: 'communication' },
      { toolName: 'loom', role: 'async-video' },
    ],
  },
  {
    name: 'AI-First Builder Kit',
    description: 'Cursor + Claude + Vercel — AI-powered development from code generation to deployment. Cursor provides AI pair programming, Claude handles complex reasoning.',
    synergyStrength: 75,
    synergyType: 'layered',
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED'],
    bestForTeamSize: ['SOLO', 'SMALL'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    confidence: 70,
    sourceCount: 15,
    sourceTypes: ['youtube_transcript', 'reddit', 'hackernews'],
    biasFlags: [],
    status: 'approved',
    tools: [
      { toolName: 'cursor', role: 'ai-editor' },
      { toolName: 'claude', role: 'ai-reasoning' },
      { toolName: 'vercel', role: 'deployment' },
    ],
  },
  {
    name: 'The Growth Engine',
    description: 'PostHog + Loops + Stripe — a data-driven growth stack. PostHog captures behavior, Loops automates outreach, Stripe handles monetization.',
    synergyStrength: 70,
    synergyType: 'sequential',
    bestForStage: ['EARLY_SEED', 'GROWTH'],
    bestForTeamSize: ['SMALL', 'MEDIUM'],
    bestForTechSavviness: ['DECENT'],
    confidence: 65,
    sourceCount: 8,
    sourceTypes: ['youtube_transcript', 'indie_hackers'],
    biasFlags: [],
    status: 'approved',
    tools: [
      { toolName: 'posthog', role: 'analytics' },
      { toolName: 'loops', role: 'email-automation' },
      { toolName: 'stripe', role: 'payments' },
    ],
  },
  {
    name: 'Design-to-Dev Pipeline',
    description: 'Figma + Linear + GitHub — designers and developers share a continuous handoff pipeline. Figma designs link to Linear issues that auto-create GitHub branches.',
    synergyStrength: 78,
    synergyType: 'sequential',
    bestForStage: ['EARLY_SEED', 'GROWTH'],
    bestForTeamSize: ['SMALL', 'MEDIUM'],
    bestForTechSavviness: ['DECENT'],
    confidence: 75,
    sourceCount: 10,
    sourceTypes: ['youtube_transcript', 'reddit'],
    biasFlags: [],
    status: 'approved',
    tools: [
      { toolName: 'figma', role: 'design' },
      { toolName: 'linear', role: 'project-management' },
      { toolName: 'github', role: 'code-host' },
    ],
  },
  {
    name: 'The Automation Trinity',
    description: 'Zapier + Notion + Slack — the classic no-code automation stack. Zapier connects everything, Notion stores structured data, Slack delivers notifications.',
    synergyStrength: 82,
    synergyType: 'hub-spoke',
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED', 'EARLY_SEED'],
    bestForTeamSize: ['SOLO', 'SMALL'],
    bestForTechSavviness: ['NEWBIE', 'DECENT'],
    confidence: 85,
    sourceCount: 25,
    sourceTypes: ['youtube_transcript', 'reddit', 'zapier_templates', 'product_hunt'],
    biasFlags: [],
    status: 'approved',
    tools: [
      { toolName: 'zapier', role: 'automation-hub' },
      { toolName: 'notion', role: 'data-store' },
      { toolName: 'slack', role: 'notification-channel' },
    ],
  },
  {
    name: 'Enterprise Compliance Stack',
    description: 'Jira + Confluence + GitHub Enterprise — enterprise-grade project management with full audit trails and SOC2/HIPAA compliance built in.',
    synergyStrength: 88,
    synergyType: 'complementary',
    bestForStage: ['GROWTH', 'ESTABLISHED'],
    bestForTeamSize: ['LARGE', 'ENTERPRISE'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    confidence: 80,
    sourceCount: 14,
    sourceTypes: ['g2_reviews', 'capterra_reviews', 'reddit'],
    biasFlags: [],
    status: 'approved',
    tools: [
      { toolName: 'jira', role: 'project-management' },
      { toolName: 'confluence', role: 'documentation' },
      { toolName: 'github', role: 'code-host' },
    ],
  },
  {
    name: 'The Content Machine',
    description: 'Notion + Canva + Buffer — content creation pipeline from ideation in Notion, design in Canva, to scheduling in Buffer.',
    synergyStrength: 65,
    synergyType: 'sequential',
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED'],
    bestForTeamSize: ['SOLO', 'SMALL'],
    bestForTechSavviness: ['NEWBIE'],
    confidence: 60,
    sourceCount: 6,
    sourceTypes: ['youtube_transcript', 'indie_hackers'],
    biasFlags: [],
    status: 'pending',
    tools: [
      { toolName: 'notion', role: 'content-planning' },
      { toolName: 'canva', role: 'design' },
    ],
  },
  {
    name: 'Async-First Remote Stack',
    description: 'Notion + Loom + Linear — designed for distributed teams that minimize meetings. Loom replaces syncs, Notion holds decisions, Linear tracks work.',
    synergyStrength: 76,
    synergyType: 'complementary',
    bestForStage: ['PRE_SEED', 'EARLY_SEED', 'GROWTH'],
    bestForTeamSize: ['SMALL', 'MEDIUM'],
    bestForTechSavviness: ['DECENT'],
    confidence: 72,
    sourceCount: 11,
    sourceTypes: ['reddit', 'hackernews', 'indie_hackers'],
    biasFlags: [],
    status: 'approved',
    tools: [
      { toolName: 'notion', role: 'knowledge-base' },
      { toolName: 'loom', role: 'async-updates' },
      { toolName: 'linear', role: 'task-tracking' },
    ],
  },
  {
    name: 'The Open Source Builder',
    description: 'GitHub + Supabase + Vercel — a fully open-source-friendly stack for indie hackers. Supabase replaces Firebase, Vercel handles deployment.',
    synergyStrength: 80,
    synergyType: 'layered',
    bestForStage: ['BOOTSTRAPPING', 'PRE_SEED'],
    bestForTeamSize: ['SOLO', 'SMALL'],
    bestForTechSavviness: ['DECENT', 'NINJA'],
    confidence: 73,
    sourceCount: 16,
    sourceTypes: ['youtube_transcript', 'reddit', 'hackernews', 'product_hunt'],
    biasFlags: [],
    status: 'approved',
    tools: [
      { toolName: 'github', role: 'code-host' },
      { toolName: 'supabase', role: 'backend' },
      { toolName: 'vercel', role: 'deployment' },
    ],
  },
  {
    name: 'The Customer Success Loop',
    description: 'Intercom + PostHog + Notion — close the feedback loop by connecting customer conversations to product analytics and documentation.',
    synergyStrength: 68,
    synergyType: 'complementary',
    bestForStage: ['EARLY_SEED', 'GROWTH'],
    bestForTeamSize: ['SMALL', 'MEDIUM'],
    bestForTechSavviness: ['DECENT'],
    confidence: 62,
    sourceCount: 7,
    sourceTypes: ['youtube_transcript', 'g2_reviews'],
    biasFlags: [],
    status: 'pending',
    tools: [
      { toolName: 'intercom', role: 'customer-support' },
      { toolName: 'posthog', role: 'analytics' },
      { toolName: 'notion', role: 'knowledge-base' },
    ],
  },
  {
    name: 'The n8n Power User',
    description: 'n8n + GitHub + Slack — self-hosted automation for technical teams. n8n workflows connect GitHub events to Slack notifications with full customization.',
    synergyStrength: 72,
    synergyType: 'hub-spoke',
    bestForStage: ['EARLY_SEED', 'GROWTH'],
    bestForTeamSize: ['SMALL', 'MEDIUM'],
    bestForTechSavviness: ['NINJA'],
    confidence: 64,
    sourceCount: 9,
    sourceTypes: ['reddit', 'hackernews', 'n8n_templates'],
    biasFlags: [],
    status: 'approved',
    tools: [
      { toolName: 'n8n', role: 'automation-engine' },
      { toolName: 'github', role: 'code-host' },
      { toolName: 'slack', role: 'notifications' },
    ],
  },
];
